---
title: "p8105_hw3_yz4717"
author: "Yang Zhao - yz4717"
date: "2023-10-09"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets) 
library(ggplot2)
data("brfss_smart2010")

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6
)
```



```{r q2_cleaning,warning=FALSE}
dict_resp = c("Poor",
              "Fair",
              "Good",
              "Very good",
              "Excellent")

brfss_df = brfss_smart2010 |> 
  janitor::clean_names() |> 
  filter(topic == "Overall Health" & response %in% dict_resp) |> 
  mutate(
    response,
    response = factor(
      response,
      levels = dict_resp,
      ordered = TRUE)) |> 
  mutate(state = locationabbr,
         county = locationdesc)

brfss_df |> head()
```


```{r q2_0201}
result_2002 = brfss_df |> 
  filter(year == 2002) |> 
  distinct(state,county)|>  
  count(state) |> 
  filter(n>=7) |> 
  pull(state)

result_2010 = brfss_df |> 
  filter(year == 2010)|> 
  distinct(state,county) |> 
  count(state) |> 
  filter(n>=7) |> 
  pull(state)

```

```{r q2_output_plot}
excellent = brfss_df |>
  filter(response == "Excellent") |> 
  select(year,state,data_value) |> 
  group_by(state,year) |> 
  summarize(mean = mean(data_value))  

excellent |> 
  ggplot(aes(x = year,y = mean, group = state,color = state)) + 
  geom_line()
```

```{r q2_outpt_boxplot}
ny_distri_df = 
  brfss_df |>  
  filter(year == 2006 | year == 2010 ) |> 
  filter(state == "NY")

ny_distri_df |> head()

ny_distr_plot=
  ny_distri_df |> 
  ggplot(aes(x=response,y = data_value))+
  geom_boxplot() +
  facet_wrap(.~year)
```

```{r q3_cleaning}
q3_factor_order = c(
  "less than high school",
  "high school equivalent",
  "more than high school"
)

covar_df = 
  read_csv("Data/nhanes_covar.csv",skip = 4) |> 
  janitor::clean_names() |> 
  mutate(sex = recode(sex, '1' = 'male', '2' = 'female')) |> 
  mutate(education = case_match(education,
                                1~"less than high school",
                                2~"high school equivalent",
                                3~"more than high school")) |> 
  filter(age>=21) |> 
  drop_na() |> 
  mutate(education = factor(education,
                            levels = q3_factor_order,
                            ordered = TRUE)) |> 
  relocate(seqn,sex,education)

accel_df = 
  read_csv("Data/nhanes_accel.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(min1:min1440,
               names_to = "time_mark",
               values_to = "values") |> 
  mutate(time_mark = substring(time_mark,first = 4),
         time_mark = as.numeric(time_mark)) 
```

```{r q3_table_for_each_catergory}
catergoried_mw_edu = covar_df |> 
  group_by(sex, education) |> 
  tally()

catergoried_mw_edu |> head()
```

```{r}
covar_df |> 
  ggplot(aes(x = age,color = sex))+
  geom_density() +
  facet_grid(.~education)
```

```{r}
total_activity_df = accel_df |> 
  group_by(seqn) |> 
  summarise(total_activity = sum(values))
```
```{r}
joint_sum_df = inner_join(covar_df,total_activity_df,by = "seqn")

joint_sum_df |> 
  ggplot(aes(x = age , y = total_activity, color = sex))+
  geom_point()+
  geom_smooth()+
  facet_grid(.~education)
```

```{r}
joint_data_df |> 
  ggplot(aes(x = age , y = total_activity, color = sex))+
  geom_point()+
  geom_smooth(method = "lm")+
  facet_grid(.~education)
```

```{r}
time_organized = accel_df |> 
  mutate(time_mark = substring(time_mark,first = 4)) 

by_minutes = inner_join(covar_df,time_organized, by = join_by("seqn"))|> 
  group_by(sex,education,time_mark)

```

